[[redirects]]
  from = "http://gdcgroup.co.nz/*"
  to = "https://gdcgroup.co.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.gdcgroup.co.nz/*"
  to = "https://gdcgroup.co.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.gdcgroup.co.nz/*"
  to = "https://gdcgroup.co.nz/:splat"
  status = 301
  force = true

# Redirect old domain to new domain
[[redirects]]
  from = "https://gdcdigital.net/*"
  to = "https://gdcgroup.co.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://gdcdigital.net/*"
  to = "https://gdcgroup.co.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.gdcdigital.net/*"
  to = "https://gdcgroup.co.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.gdcdigital.net/*"
  to = "https://gdcgroup.co.nz/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Robots-Tag = "index, follow"
    Cache-Control = "public, max-age=31536000, immutable"